name: Release Management

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Lowercase Repository
      id: repo
      run: |
        REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "repo=$REPO" >> $GITHUB_OUTPUT

    - name: Generate Version
      id: version
      run: |
        # If a tag was pushed, use that tag
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          VERSION="${{ github.ref_name }}"
        else
          # Generate timestamp-based version
          VERSION="v0.1.0-$(date +'%Y%m%d%H%M%S')"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/heads/main')
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        generate_release_notes: true

    - name: Log in to Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ steps.repo.outputs.repo }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ steps.repo.outputs.repo }}:${{ steps.version.outputs.VERSION }}
          ${{ env.REGISTRY }}/${{ steps.repo.outputs.repo }}:latest
        labels: ${{ steps.meta.outputs.labels }}
